_BASE_: "Base-OneNet.yaml"
MODEL:
  WEIGHTS: "torchvision-R-18.pkl"
  BACKBONE:
      FREEZE_AT: 0
  RESNETS:
    NORM: "BN"
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
  OneNet:
    DCN: False
    NUM_CLASSES: 80
    DECONV_CHANNEL: (512, 256, 128, 64)
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 64
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: 'output_onenet_r18nodcn'
